# drop_list = [
#                'N',
#                '#ID',
#                'Data Nascita',
#                'Data Arruol.',
#                'Età Arruol.',
#                'Data Prelievo',
#                'Cognome',
#                'Nome',
#                'Consenso Dati',
#                'Consenso Sangue',
#                'Consenso Urine',
#                'Fratello',
#                'Sorella',
#                'Digiuno P',
#                'Prelievo P',
#                'Stato fisico Prelievo P',
#                'Profilo x Prelievo',
#                'Digiuno U',
#                'Prelievo U',
#                'Stato fisico Prelievo U',
#                'LUC (%)',
#                'LUC  (10^3/mmc)',
#                'PDW-Distr.Vol.Piastrine (%)',
#                'Gamma GT (u/l)',
#                'LDH (U/L)',
#                'U.I.B.C.  (microgr/dl)',
#                'TIBC ( (microgr/dl)',
#                'Ab anti recettori del TSH (UI/L)',
#                'eGFR (mL/min) ',
#                'Ab antiendomisio' ,
#                'lactate+threonine',
#                'glycerol',
#                'unk2',
#                'succ.>21.5',
#                'Heart Notes',
#                'Urine',
#                '    glutamate',
#                'fumarate.1',
#                'dimethylglycine+x',
#                'allantoin',
#                'acetone.1',
#                'Isoleucine',
#                'leucine.1',
#                'valine.1',
#                'alanine.1',
#                'asparagine',
#                'CreatineCreatinine',
#                'citrate.1',
#                'glycine.1',
#                'ethanolamine',
#                '4-hydroxyphenylacetate',
#                '3-hydroxyisovalericacid',
#                'dimethylamine',
#                'trimethylamine-N-oxide',
#                'taurine',
#                'creatine.1',
#                'glycolate',
#                'creatinine.1',
#                'cis-aconitate',
#                'tyrosine.1',
#                'hippurate',
#                'formate.1',
#                'trigonelline',
#                '1-methylnicotinamide',
#                'ascorbate',
#                'indoxylsulfate',
#                'phenylacetylglycine',
#                '2-hydroxyisobutyricacid',
#                'glu-gln',
#                'glucose.1',
#                'lysine.1',
#                'Name W',
#                'Code',
#                'Collected by',
#                'Examination Date',
#                'Surname',
#                'Name',
#                'Sex',
#                'Birth',
#                'Birth City',
#                'Mother Birth',
#                'Father Birth',
#                'General Notes',
#                'Mosaic Percentage',
#                'Trisomy Notes',
#                'Birth Notes',
#                'Head Notes',
#                'Abdomen Notes',
#                'Skeletal Notes',
#                'Neurologic Notes',
#                'Other Notes',
#                'Event',
#                'Fosfatasi alcalina (U/L)',
#                "Apgar Score 5'",
#                'CD+3HLA-DR+ (T Attivati) (%)',
#                'CD3+/gamma+delta+ (%)',
#                'Calcio totale (mg/dl) ',
#                'SAT Fe (%)',
#                'Proteina C Reattiva (mg/dL)',
#                'Titolo anti Streptolisinico ( U/mL)',
#                'Insulina (microU/mL)',
#                'Poor Moro Reflex',
#                'Saturazione TRF%',
#                'Atypical Fingerprints',
#                'First Sibling Birth',
#                'First Sibling Sex',
#                'Second Sibling Birth',
#                'Second Sibling Sex',
#                'Third Sibling Birth',
#                'Third Sibling Sex',
#                'Fourth Sibling Birth',
#                'Fourth Sibling Sex',
#                'Fifth Sibling Birth',
#                'Fifth Sibling Sex',
#                'Sixth Sibling Birth',
#                'Sixth Sibling Sex',
#                'Seventh Sibling Birth',
#                'Seventh Sibling Sex',
#                'Eighth Sibling Birth',
#                'Eighth Sibling Sex',
#                'First Miscarriage',
#                'Second Miscarriage',
#                'Third Miscarriage',
#                'Fourth Miscarriage',
#                'Padova',
#                'Name G',
#                'Birth G',
#                'Date G',
#                'Age G',
#                'Gender G',
#                'A Raw G',
#                'B Raw G',
#                'B AE G',
#                'Children Number',
#                'In Vitro Fertilization',
#                'Natural Delivery',
#                'Free vs Translocated',
#                'Complete vs Partial',
#                'Homogeneous vs Mosaic',
#                'Inheritance',
#                'Blood',
#                'Amniocentesis',
#                'Villocentesis',
#                'Funicolocentesis',
#                'Karyotype',
#                'Weight Percentile',
#                'Echoencephalography',
#                'Atlantoaxial Instability',
#                'Hypoplastic Iliac Wings',
#                'Test',
#                'Gestational Age',
#                'Gestational Age.1',
#                'Birth W',
#                'Date W',
#                'TSH Test Date',
#                'SuperTable',
#                'Età al Prelievo',
#                'WBC (10^3/microL)',
#                'Age at Exam yrs'
# ]

categorical_list = [
    'Sex',
    'Short Stature',
    'Flat Occiput [Plagiocephaly]',
    'Flat Facial Profile',
    'Small Ears',
    'Hearing Loss',
    'Strabismus',
    'Myopia',
    'Heart Surgery',
    'Separation of the Abdominal Muscle',
    'Umbilical Hernia',
    'Duodenal Atresia',
    'Imperforate Anus',
    'Hirschprung Disease',
    'Mental Retardation Severity',
    'Obstructive Sleep Apnea',
    'Seizures',
    'Hypothyroidism',
    'Alopecia',
    'Celiac Disease',
    'Small Genitalia',
    'Masticatory Disfunction',
    'Constipation',
    'Diarrhea',
    'MTHFR Genotype'
]
